name: muzik_audio_player
description: Music Audio Player.

publish_to: 'none'
version: 0.4.11+5
environment:
  sdk: ">=2.12.0 <3.0.0"

#  Run build task -> flutter packages pub run build_runner build
#  Run build task -> dart pub run build_runner build
#  options :
#     --delete-conflicting-outputs
#     --help

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  cupertino_icons: ^1.0.5
  font_awesome_flutter: ^10.1.0

  package_info_plus: ^3.0.1
  device_info_plus: ^7.0.1


  path_provider: ^2.0.11
  share_plus: ^6.0.1
  #share: ^0.6.5+1

  url_launcher: ^6.1.6

  #flutter_audio_query: ^0.3.5+6

  #audio_service: ^0.17.1

  #audioplayers: ^0.18.3
  #audio_session: ^0.1.5
  rxdart: ^0.27.5

  just_audio: ^0.9.30
  just_audio_background: ^0.0.1-beta.8

  flutter_bloc: ^7.3.2 #^8.1.1
  equatable: ^2.0.5


  #sqflite: ^1.3.1+1
  #cloud_firestore: any
  #firebase_core: ^1.6.0
  #firebase_auth: ^3.1.1
  #firebase_database: ^4.0.0

  #on_audio_query: ^2.3.1
  on_audio_query: ^2.6.1

  on_audio_room: ^2.2.1+1
  #music: ^1.0.3
  marquee: ^2.2.0
  animated_text_kit: ^4.2.1

  objectbox: ^1.2.0
  objectbox_flutter_libs: ^1.2.0
  #objectbox_flutter_libs: any

  intl: ^0.17.0

  flutter_launcher_icons: ^0.10.0

  get: ^4.6.5
  indexed_list_view: ^2.0.1
  permission_handler: ^10.2.0
  #permission_handler: ^10.0.1
  json_serializable: ^6.4.0

  page_transition: ^2.0.9


dev_dependencies:
  #build_runner: ^1.0.0
  build_runner: ^2.1.4
  objectbox_generator: any
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0

# The following information id for app_launcher_icon,
flutter_icons:
  image_path: "assets/app_icon.png"
  #image_path_android: "assets/images/icon-710x599-android.png"
  #image_path_ios: "assets/images/icon-1024x1024.png"
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"
  #adaptive_icon_background: "assets/images/christmas-background.png" # only available for Android 8.0 devices and above
  #adaptive_icon_foreground: "assets/images/icon-foreground-432x432.png" # only available for Android 8.0 devices and above


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  generate: true

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true


  assets:
    - assets/app_icon.png
    - assets/cardi_b.jpg
    - assets/icon/artist.png
    - assets/icon/fav_song.png
    - assets/icon/fav_song_r.png
    - assets/icon/file_song.png
    - assets/icon/no_song.png
    - assets/no_cover.png
    - assets/no_cover1.png
    - assets/no_cover2.png
    - assets/no_cover4.png
    - assets/passenger-let-her-go.jpg
    - assets/playlist_img.png
    - assets/playlist_img1.png
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:

  fonts:
    - family: ubuntu
      fonts:
        - asset: fonts/Ubuntu-Medium.ttf
        - asset: fonts/Ubuntu-MediumItalic.ttf
          style: italic
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
