/// Generated by AssetsRefGenerator on 2021/10/31
class Res {
  static const String app_icon = "assets/app_icon.png";
  static const String cardi_b = "assets/cardi_b.jpg";
  static const String no_cover = "assets/no_cover.png";
  static const String no_cover1 = "assets/no_cover1.png";
  static const String no_cover2 = "assets/no_cover2.png";
  static const String no_cover4 = "assets/no_cover4.png";
  static const String passenger_let_her_go = "assets/passenger-let-her-go.jpg";
  static const String playlist_img = "assets/playlist_img.png";
  static const String playlist_img1 = "assets/playlist_img1.png";
}
